In [3]:
from sklearn.datasets import  load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [5]:
iris=load_iris()

In [9]:
l_score=cross_val_score(LogisticRegression(),iris.data,iris.target)
l_score

C:\Users\Asus TUF\anaconda3.0\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [13]:
np.average(l_scores)

0.9733333333333334

In [17]:
d_score=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_score

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [19]:
np.average(d_score)

0.9533333333333334

In [21]:
s_score=cross_val_score(SVC(),iris.data,iris.target)
s_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [25]:
np.average(s_score)

0.9666666666666666

In [23]:
r_score=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
r_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [27]:
np.average(r_score)

0.96

In [ ]:
l_score have the most big value()()()()()()()()()()()()())()()()()()()()()